# Generated by Django 3.2.18 on 2023-04-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('brand', models.CharField(blank=True, max_length=254, null=True)),
                ('promotion_qr_code', models.CharField(blank=True, max_length=254, null=True)),
                ('barcode', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wholsale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_no', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('img_paths', models.ImageField(blank=True, null=True, upload_to='')),
                ('mark_up', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('on_carousel_one', models.BooleanField(default=False)),
                ('on_carousel_two', models.BooleanField(default=False)),
                ('on_carousel_three', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
